"""
Django settings for brewbackend project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
from django.utils.csp import CSP


# Build paths inside the project like this:
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = 'django-insecure-bgmeo$6ol^=5^ypp3x&@=pdf5tpp1z9c4kzwmzf=y3mxbz(upc'

DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'corsheaders',
    'rest_framework',

    # Your app
    'cafe',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    # CORS
    'corsheaders.middleware.CorsMiddleware',

    # Django security
    'django.middleware.security.SecurityMiddleware',

    # Django 6.0 built-in CSP
    'django.middleware.csp.ContentSecurityPolicyMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # CSRF protection
    'django.middleware.csrf.CsrfViewMiddleware',

    # Authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    # Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'brewbackend.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'brewbackend.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# CORS
# =========================================================

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]


# =========================================================
# CSRF
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# =========================================================
# CONTENT SECURITY POLICY (Django 6.0)
# =========================================================

SECURE_CSP = {
    'default-src': [
        CSP.SELF,
    ],

    # JavaScript
    'script-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
    ],

    # CSS + Google Fonts
    'style-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
        'https://fonts.googleapis.com',
    ],

    # Images
    'img-src': [
        CSP.SELF,
        'data:',
        'https:',
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ],

    # Fonts
    'font-src': [
        CSP.SELF,
        'https://fonts.gstatic.com',
    ],

    # React -> Django API
    'connect-src': [
        CSP.SELF,
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ],

    # Iframes
    'frame-src': [
        CSP.SELF,
        'https://www.google.com',
    ],

    # Prevent clickjacking
    'frame-ancestors': [
        CSP.NONE,
    ],

    # Forms
    'form-action': [
        CSP.SELF,
    ],
}